spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.80.114:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
           - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
           - Query=url,qq

server:
  port: 88
